language: cpp
compiler: gcc
env:
  global:
  - APT_DEPENDENCIES="doxygen doxygen-latex libboost-all-dev libeigen3-dev liblapack-dev
    libblas-dev gfortran python-dev python-sphinx python-numpy libbullet-dev
    ros-groovy-angles ros-groovy-common-msgs ros-groovy-control-msgs 
    ros-groovy-pr2-controllers ros-groovy-resource-retriever
    ros-groovy-robot-state-publisher ros-groovy-ros-base ros-groovy-angles
    ros-groovy-rosdoc-lite	ros-groovy-tf ros-groovy-urdf"
  - GIT_DEPENDENCIES="jrl-umi3218/jrl-mathtools jrl-umi3218/jrl-mal laas/abstract-robot-dynamics jrl-umi3218/jrl-dynamics
    stack-of-tasks/dynamic-graph stack-of-tasks/dynamic-graph-python stack-of-tasks/sot-core
    stack-of-tasks/sot-tools stack-of-tasks/sot-dynamic laas/jrl_dynamics_urdf"
  - ROS_VERSION=groovy
  - ROS_GIT_DEPENDENCIES="francois-keith/dynamic_graph_bridge_msgs:catkin"
  - ALLOW_CATKINLINT_FAILURE=true
notifications:
  email:
  - francois.keith@gmail.com
branches:
  only:
  - master
  - groovy
  - groovy_rebased
  - catkin
  - catkin_groovy
  - travis
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install: ./.travis/run dependencies/catkin; ./.travis/run before_install

